name: Rapport de couvertures
run-name: Gérez un projet collaboratif en intégrant une démarche CI/CD
on: [push]
jobs:
  test-coverages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - run: ng test --code-coverage
