name: Docker deploiement
run-name: Docker deploiement
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Récupère le code
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Met en place la machine virtuelle
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Met en placce Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Déploie le front sur Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: sebastiendev1/bobapp-front:latest

      # Déploie le back sur Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: sebastiendev1/bobapp-back:latest