name: Qualité du code
run-name: Gérez un projet collaboratif en intégrant une démarche CI/CD
on: [push]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the dependencies MVN in the back folder
        run: mvn clean install
        working-directory: ./back
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}