name: Rapport de couvertures
run-name: Gérez un projet collaboratif en intégrant une démarche CI/CD
on: [push]
jobs:
  test-coverages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the dependencies NPM in the front folder
        run: npm ci
        working-directory: ./front
      - name: Install Angular
        run: npm install -g @angular/cli
      - name: Generate the code coverage
        run: ng test --code-coverage --browsers=ChromeHeadless --watch=false
        working-directory: ./front
      - name: Save the coverage
        uses: actions/upload-artifact@v4
        with:
            name: front-coverage
            path: ./front/coverage