name: Docker deploiment
run-name: Docker deploiment
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: sebastiendev1/bobapp-front:latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./back
          push: true
          tags: sebastiendev1/bobapp-back:latest